### ISSUE TITLE
TEMSI WINTEM

### ISSUE THREAD

**Issue by Alfourbe** [FoxP/Weather-Logger#1]
Hi
thank you for sharing your code, I am french (sorry for my english) and from an Airclub in the south, and I was looking for a code to display the weather on our Raspberry that displays info about our club in the lobby.
I modified a little your code to retrieve also EUROC/TEMSI and WINTEM in pdf, I can send it to you if you are interesting to merge it with your current version.
Anyhow thank you, you make me save lot of time :)
Regards
AL

**Comment by FoxP** [comment]
Hi !
Don't hesitate to do a pull request with your modifications, i'll be happy to properly merge it !
By the way, i'm french too. Merci à vous ! :+1:

**Comment by Alfourbe** [comment]
Hi
sorry, 1st time I use Github, and Iyt seems to pull request it needs a branch, but I can't create one, I attach the file there.
What is missing in the code is parameter in .ini to active/deactivate WINTEM and TEMSI
If you fly by LFMD let me know
Cheers
[config.ini.txt](https://github.com/FoxP/Weather-Logger/files/1856118/config.ini.txt)
[METAR_TAF_logger2.py.txt](https://github.com/FoxP/Weather-Logger/files/1856119/METAR_TAF_logger2.py.txt)

**Comment by FoxP** [comment]
Fixed by https://github.com/FoxP/Weather-Logger/commit/159eb3d21810b1a523b138b6b18c13deab5724fd, thanks !
I added you to the contributors.
