### ISSUE TITLE
Where do you get the user_code ?

### ISSUE THREAD

**Issue by redge76** [FoxP/Weather-Logger#2]
How do you get a user_code ? I can't find anything on the web site.

**Comment by FoxP** [comment]
It's your 10 digits aeronautical code. If you fly you should have one.

**Comment by redge76** [comment]
I do fly (ULM + aircraft) but I don't see what the 10 digit code is.
I have an aeroweb login.  The old access code was the FNA license number. But it's not 10 digit.

**Comment by FoxP** [comment]
OK, i updated the **README.md** file. :+1:

**Comment by redge76** [comment]
pourquoi effacer la discussion ?
pas de doute on est en France le pays du formulaire paper... :-(

**Comment by FoxP** [comment]
J'ai effacé mon message pour n'induire personne en erreur, j'avais tout faux. Du coup j'ai préféré directement intégrer la réponse que j'ai obtenu de l'équipe webmaster d'AEROWEB dans la documentation. 

Et oui, je suis d'accord, c'est bien dommage pour le formulaire papier !
